### ISSUE TITLE
Light level overlay should be main hand only

### ISSUE THREAD

**Issue by nopeless** [ComplementaryDevelopment/ComplementaryReimagined#13]
Rather small detail but I don't think light level overlay when `Hold light source` should be on when light source is in offhand

**Comment by EminGT** [comment]
That was the case on an old version of Comp v4, but a bunch of people requested me to make it work on the off hand as well. Turns out a lot of people use the feature when mining, and holding a tool on the main hand is preferable for them

**Comment by nopeless** [comment]
> That was the case on an old version of Comp v4, but a bunch of people requested me to make it work on the off hand as well. Turns out a lot of people use the feature when mining, and holding a tool on the main hand is preferable for them

I'm sorry for commenting on a closed issue but can you briefly explain to me how it is useful in mining?

**Comment by EminGT** [comment]
To prevent mobs from spawning in the caves near you, you need to light them up. This means lighting up everywhere when exploring the caves can be a good idea. But you probably also want to use a pickaxe and a sword, so your torches should go on the off-hand. Since you want to light the cave perfectly, the light level overlay can be useful
