### ISSUE TITLE
Reflection aren't rendered when object in the reflection is hidden from view

### ISSUE THREAD

**Issue by Clozent** [ComplementaryDevelopment/ComplementaryReimagined#15]
When you look at something's reflection on water and move so it is covered by something else, the part of it that is covered will also disappear in the reflection.
I have a video recording of it, as an example.
https://youtu.be/FTEii9_DIyA

This probably happens any time an object isn't rendered, since if the player doesn't look at an object, it's reflection will disappear as well.

**Comment by EminGT** [comment]
Hello. This is a limitation of doing fast reflections in Minecraft. The
objects that can't be seen by the player cannot be reflected on the water.
In your video, leaves of the tree are blocking the terrain that is supposed
to be reflected. If this is bothering you, you can change the Water Style
option to "Fantasy" to make the problem way less noticeable.

**Comment by Clozent** [comment]
But why? This is really hurting the experience. The "Fantasy" style looks like any other shader's water and the "Reimagined" style is cool and unique. Why not have an option for it? This way, people with more capable computers can turn it on and enjoy better reflections.

**Comment by EminGT** [comment]
I understand your frustration about this problem, because I am frustrated about it as well. There really isn't a great way to do this in Minecraft. Some effects can't be made an option, and this is one of them. It would cost insane performance (get your current fps and divide it by 2) to even have the option added. I might figure out something else to hide the limitations in the future, but for now this is really the best we can do.

**Comment by EminGT** [comment]
I think some kind of overscan could be added. I need to take a look at the specifics about resolution dropping though. The easy way to do it would reduce the resolution of the image
