### ISSUE TITLE
game crashes when right clicking with a wind charge

### ISSUE THREAD

**Issue by thefurnaceguy** [ComplementaryDevelopment/ComplementaryReimagined#163]
when right clicking with a wind charge and then it impacts on the floor, the game frozes for a second then it crashes xD

i don't know why this happens, but i hope its just a shader or mod issue

i'll leave my shader settings and the mods i use below.

![image](https://github.com/user-attachments/assets/ffb04737-936c-4fdb-870b-43e78bdffac9)
[ComplementaryReimagined_r5.3.zip.txt](https://github.com/user-attachments/files/18001569/ComplementaryReimagined_r5.3.zip.txt)

please let me know, thanks!

**Comment by EminGT** [comment]
Also download Iris 1.8.3. I think 1.8.2 might have a problem

**Comment by thefurnaceguy** [comment]
> There is absolutely no way this is in any way related to Complementary. I recommend you test without any extra mods

_it is_ related to the shader; tried on another shaders such as Super Duper Vanilla and it didn't crash.

**Comment by EminGT** [comment]
Shaders can not make the game crash in that way. And a problem only happening on certain shaders still does not mean the problem is related to the shader. It can be a mod trying to mess with the rendering, or a mod incompatibility with Iris, or an internal Iris problem in general. But a crash like that simply isn't related to shaderpacks themselves
