### ISSUE TITLE
Screen space global illumination

### ISSUE THREAD

**Issue by g6d3np81** [ComplementaryDevelopment/ComplementaryReimagined#28]
I have zero knowledge in GLSL.
Is there any plan to implement SSGI?

Chocapic13 seems abandoned at this point and I don't know of any other shader that does SSGI. Would be nice to have this for extra eye candy. Assuming it will cost around 2x-4x the cost of SSAO then it can be feasible on lower end machine.

Completely blind guessing the performance cost here, although I have run Chocapic on gtx970 1080p 60fps without much trouble so... maybe not that far off (I hope).

**Comment by EminGT** [comment]
SSGI could be nice but it requires the shaderpack to use deferred-rendering, which causes a couple unfixable bugs in the current Optifine shader pipeline. It could be made better in Iris but I don't want to drop support for Optifine anytime soon, and I can't add it as an option because deferred-rendering requires a big rewrite of some parts of the code.
