### ISSUE TITLE
Mod support

### ISSUE THREAD

**Issue by Aulberon** [ComplementaryDevelopment/ComplementaryReimagined#4]
I'm not sure how hard it would be, but it would be awesome if this shaderpack worked with these two mods:
https://www.curseforge.com/minecraft/mc-mods/portable-hole
https://www.curseforge.com/minecraft/mc-mods/droplight

**Comment by EminGT** [comment]
Supporting mods in the shaderpack is a very problematic process, as often supporting one thing breaks another, and support for multiple mods eventually start to hurt the performance. The two mods you mentioned are relatively unpopular mods too, so I don't think they deserve specific mod support. I feel like it would make more sense if the mod developers supported shaderpacks instead of the opposite. Especially the Droplight mod seems like it could have worked fine with all shaderpacks if the effect was designed in a different way

**Comment by Aulberon** [comment]
Thanks for the answear. I will try and contact the devs of these mods.
