### ISSUE TITLE
Potential Bug with emissive Block Display entities 

### ISSUE THREAD

**Issue by ToastyDark** [ComplementaryDevelopment/ComplementaryReimagined#70]
Hello, I was trying to spawn a Respawn Anchor using block displays while keeping emissive texture but it does not seem possible. Spawning a block entity with brightness set to 15 spawns a glowing respawn anchor, but is missing Complementary's overlay.

![2024-01-09_22 07 30](https://github.com/ComplementaryDevelopment/ComplementaryReimagined/assets/31451604/e4eeb690-f9ef-471a-a360-2ea87c82254a)

The Block Display in this case is in the middle, while a real Respawn Anchor is on the right for reference. Interestingly, if you summon an item display as a Respawn Anchor, it actually keeps its emissive overlay (the one on the left.) Unfortunately though, you cannot spawn a respawn anchor as an item display with the charge set to 4 (afaik) because item displays don't support block state tags.

I was wondering if the block displays don't have an emissive texture because of a Complementary bug, an Iris bug, or a vanilla limitation.

Minecraft: 1.20.2
Sodium: v0.5.5
Iris: v1.6.14
Complementary: r5.1.1

Block Display Command:  ```summon minecraft:block_display ~ ~1.5 ~ {block_state:{Name:"minecraft:respawn_anchor",Properties:{charges:"4"},Count:1},interpolation_duration:0,start_interpolation:0,view_range:20f,shadow_radius:0f,shadow_strength:0f,brightness:{sky:13,block:13}}```

Item Display Command: ```summon minecraft:item_display ~ ~2 ~ {item:{id:"minecraft:respawn_anchor",Count:1b,tag:{BlockStateTag:{charges:"4"}}},interpolation_duration:0,start_interpolation:0,view_range:20f,shadow_radius:0f,shadow_strength:0f,brightness:{sky:13,block:13}}```

**Comment by EminGT** [comment]
This is because neither shader loaders (Optifine, Iris) tell the shader about block display entities. The only information shader has about the block display is the fact that it has the ID of "minecraft:block_display" which can't be used to apply and block specific effects. Meanwhile Iris does (Optifine still doesn't) give the shader a decent block ID for items that look like blocks, so I use that to make sure the materials get applied for items. I will ask the developer of Iris about possibly extending the item ID system for block displays but it may not be feasible. We will see

**Comment by EminGT** [comment]
Looks like this will be eventually fixed in Iris
