### ISSUE TITLE
What mods are supported?

### ISSUE THREAD

**Issue by Pol076** [ComplementaryDevelopment/ComplementaryReimagined#87]
Hi! I want to use this shader pack for a build with customs light sources but i have an issue where the light that come from the simplylight mod have a lower brightness than vanilla light sources and the light that thew emit have a weird flickering when I don't move the camera and some weird artifacts when I move .I don't need this mod in particular so if you could send me a list of mods that you officialy support , it would be helpful for me.

**Comment by Pol076** [comment]
Also I forgot to metion that I use the Oculus shader loader on forge on minecraft 1.19.2 and my gpu is a gtx1660ti

**Comment by EminGT** [comment]
There isn't a list of mods that are supported, because about 95% of mods don't need specific support from shaders. The 5% that do are usually doing something stupid to break shaders. Most of the time that I contact the mod developers about their mods breaking shaders for any reason, they usually tell me that they simply don't care about shaders and have zero interest in spending any time to make it compatible. I did my best in Complementary to make sure the shader pipeline is as close to vanilla as possible in order to ensure best mod compatibility, but this doesn't change anything when the mod is actively attacking the pipeline on an underlying level.

This is unfortunately just how it is with Minecraft mods. Mod developers that care about shaders at all will make their mod work perfectly with them, but the 5% that don't care or actively hate shaders will do things that break the visuals. There isn't much I can do to fix most of these problems. Even if I can fix like one tenth of them using weird workarounds, it would be a fight that I can't win. There are new shader-breaking mods getting released almost every day. All we can do is to accept this reality and not use mods that break shaders, or just let those mod developers win and stop using shaders.

**Comment by Pol076** [comment]
It actually was juste me messing with the sader setting and probably activating something m'y GPU couldn't handle .I reseted the shader and now everything works properly. Still thanks you for your answer!
