### ISSUE TITLE
Clouds (and Nebula sky) are rendered on top of everything in sight.

### ISSUE THREAD

**Issue by PierreV23** [ComplementaryDevelopment/ComplementaryReimagined#90]
Clouds and Nebula sky are rendered in front of blocks / buildings, so i can see clouds while indoors.

Im using default settings, I also tried the Very Low and Medium profiles but they suffer the same issue.

**Comment by EminGT** [comment]
This doesn't happen for our thousands of users, so I don't think this is a shader bug. It's likely caused by something else. You can ask for support in the Complementary Discord server if you want. You will need to provide a lot of detail and media for anyone to be able to help you though, because as I said this doesn't happen for anyone else I've seen

**Comment by PierreV23** [comment]
> This doesn't happen for our thousands of users, so I don't think this is a shader bug. It's likely caused by something else. You can ask for support in the Complementary Discord server if you want. You will need to provide a lot of detail and media for anyone to be able to help you though, because as I said this doesn't happen for anyone else I've seen

Im not sure how my issue was placed here, but my issue was supposed to be placed on a fork of Complementary Reimagined that has some Distant Horizons compability options. Oopsie!
